### ISSUE TITLE
Hidden files included in add-on zip

### ISSUE THREAD

**Issue by sidane** [xf-liam/AlterEgoDetector#4]
The add-on zip from XenForo.com includes various hidden files.

Examples:
- upload/library/LiamW/.DS_Store
- upload/library/LiamW/AlterEgoDetector/.git/*
- upload/library/LiamW/AlterEgoDetector/.idea/*
- and more...

People (like me) using the command line to recursively copy the add-on files into their site will get these extra files when they don't need/want them.

Relates to v1.4.5, haven't checked older versions.

**Comment by formerandroider** [comment]
I'll create a script that ignores the hidden files & directories for next time.

I just copy the entire directory usually.

Liam
